export interface State {
  id: string;
  name: string;
}

export interface LGA {
  id: string;
  name: string;
  state_id: string;
}

export const states: State[] = [
  { id: "1", name: "Abia" },
  { id: "2", name: "Adamawa" },
  { id: "3", name: "Akwa Ibom" },
  { id: "4", name: "Anambra" },
  { id: "5", name: "Bauchi" },
  { id: "6", name: "Bayelsa" },
  { id: "7", name: "Benue" },
  { id: "8", name: "Borno" },
  { id: "9", name: "Cross River" },
  { id: "10", name: "Delta" },
  { id: "11", name: "Ebonyi" },
  { id: "12", name: "Edo" },
  { id: "13", name: "Ekiti" },
  { id: "14", name: "Enugu" },
  { id: "15", name: "Federal Capital Territory" },
  { id: "16", name: "Gombe" },
  { id: "17", name: "Imo" },
  { id: "18", name: "Jigawa" },
  { id: "19", name: "Kaduna" },
  { id: "20", name: "Kano" },
  { id: "21", name: "Katsina" },
  { id: "22", name: "Kebbi" },
  { id: "23", name: "Kogi" },
  { id: "24", name: "Kwara" },
  { id: "25", name: "Lagos" },
  { id: "26", name: "Nasarawa" },
  { id: "27", name: "Niger" },
  { id: "28", name: "Ogun" },
  { id: "29", name: "Ondo" },
  { id: "30", name: "Osun" },
  { id: "31", name: "Oyo" },
  { id: "32", name: "Plateau" },
  { id: "33", name: "Rivers" },
  { id: "34", name: "Sokoto" },
  { id: "35", name: "Taraba" },
  { id: "36", name: "Yobe" },
  { id: "37", name: "Zamfara" }
];

export const lgas: LGA[] = [
  // Abia
  { id: "1", name: "Aba North", state_id: "1" },
  { id: "2", name: "Aba South", state_id: "1" },
  { id: "3", name: "Arochukwu", state_id: "1" },
  { id: "4", name: "Bende", state_id: "1" },
  { id: "5", name: "Ikwuano", state_id: "1" },
  { id: "6", name: "Isiala Ngwa North", state_id: "1" },
  { id: "7", name: "Isiala Ngwa South", state_id: "1" },
  { id: "8", name: "Isuikwuato", state_id: "1" },
  { id: "9", name: "Obi Ngwa", state_id: "1" },
  { id: "10", name: "Ohafia", state_id: "1" },
  { id: "11", name: "Osisioma", state_id: "1" },
  { id: "12", name: "Ugwunagbo", state_id: "1" },
  { id: "13", name: "Ukwa East", state_id: "1" },
  { id: "14", name: "Ukwa West", state_id: "1" },
  { id: "15", name: "Umuahia North", state_id: "1" },
  { id: "16", name: "Umuahia South", state_id: "1" },
  { id: "17", name: "Umu Nneochi", state_id: "1" },

  // Adamawa
  { id: "18", name: "Demsa", state_id: "2" },
  { id: "19", name: "Fufure", state_id: "2" },
  { id: "20", name: "Ganye", state_id: "2" },
  { id: "21", name: "Gayuk", state_id: "2" },
  { id: "22", name: "Gombi", state_id: "2" },
  { id: "23", name: "Grie", state_id: "2" },
  { id: "24", name: "Hong", state_id: "2" },
  { id: "25", name: "Jada", state_id: "2" },
  { id: "26", name: "Larmurde", state_id: "2" },
  { id: "27", name: "Madagali", state_id: "2" },
  { id: "28", name: "Maiha", state_id: "2" },
  { id: "29", name: "Mayo Belwa", state_id: "2" },
  { id: "30", name: "Michika", state_id: "2" },
  { id: "31", name: "Mubi North", state_id: "2" },
  { id: "32", name: "Mubi South", state_id: "2" },
  { id: "33", name: "Numan", state_id: "2" },
  { id: "34", name: "Shelleng", state_id: "2" },
  { id: "35", name: "Song", state_id: "2" },
  { id: "36", name: "Toungo", state_id: "2" },
  { id: "37", name: "Yola North", state_id: "2" },
  { id: "38", name: "Yola South", state_id: "2" },

  // Lagos
  { id: "39", name: "Agege", state_id: "25" },
  { id: "40", name: "Ajeromi-Ifelodun", state_id: "25" },
  { id: "41", name: "Alimosho", state_id: "25" },
  { id: "42", name: "Amuwo-Odofin", state_id: "25" },
  { id: "43", name: "Apapa", state_id: "25" },
  { id: "44", name: "Badagry", state_id: "25" },
  { id: "45", name: "Epe", state_id: "25" },
  { id: "46", name: "Eti-Osa", state_id: "25" },
  { id: "47", name: "Ibeju-Lekki", state_id: "25" },
  { id: "48", name: "Ifako-Ijaiye", state_id: "25" },
  { id: "49", name: "Ikeja", state_id: "25" },
  { id: "50", name: "Ikorodu", state_id: "25" },
  { id: "51", name: "Kosofe", state_id: "25" },
  { id: "52", name: "Lagos Island", state_id: "25" },
  { id: "53", name: "Lagos Mainland", state_id: "25" },
  { id: "54", name: "Mushin", state_id: "25" },
  { id: "55", name: "Ojo", state_id: "25" },
  { id: "56", name: "Oshodi-Isolo", state_id: "25" },
  { id: "57", name: "Shomolu", state_id: "25" },
  { id: "58", name: "Surulere", state_id: "25" },

  // Rivers
  { id: "59", name: "Abua-Odual", state_id: "33" },
  { id: "60", name: "Ahoada East", state_id: "33" },
  { id: "61", name: "Ahoada West", state_id: "33" },
  { id: "62", name: "Akuku-Toru", state_id: "33" },
  { id: "63", name: "Andoni", state_id: "33" },
  { id: "64", name: "Asari-Toru", state_id: "33" },
  { id: "65", name: "Bonny", state_id: "33" },
  { id: "66", name: "Degema", state_id: "33" },
  { id: "67", name: "Eleme", state_id: "33" },
  { id: "68", name: "Emohua", state_id: "33" },
  { id: "69", name: "Etche", state_id: "33" },
  { id: "70", name: "Gokana", state_id: "33" },
  { id: "71", name: "Ikwerre", state_id: "33" },
  { id: "72", name: "Khana", state_id: "33" },
  { id: "73", name: "Obio-Akpor", state_id: "33" },
  { id: "74", name: "Ogba-Egbema-Ndoni", state_id: "33" },
  { id: "75", name: "Okrika", state_id: "33" },
  { id: "76", name: "Omuma", state_id: "33" },
  { id: "77", name: "Opobo-Nkoro", state_id: "33" },
  { id: "78", name: "Oyigbo", state_id: "33" },
  { id: "79", name: "Port Harcourt", state_id: "33" },
  { id: "80", name: "Tai", state_id: "33" },

  // Kano
  { id: "81", name: "Ajingi", state_id: "20" },
  { id: "82", name: "Albasu", state_id: "20" },
  { id: "83", name: "Bagwai", state_id: "20" },
  { id: "84", name: "Bebeji", state_id: "20" },
  { id: "85", name: "Bichi", state_id: "20" },
  { id: "86", name: "Bunkure", state_id: "20" },
  { id: "87", name: "Dala", state_id: "20" },
  { id: "88", name: "Dambatta", state_id: "20" },
  { id: "89", name: "Dawakin Kudu", state_id: "20" },
  { id: "90", name: "Dawakin Tofa", state_id: "20" },
  { id: "91", name: "Doguwa", state_id: "20" },
  { id: "92", name: "Fagge", state_id: "20" },
  { id: "93", name: "Gabasawa", state_id: "20" },
  { id: "94", name: "Garko", state_id: "20" },
  { id: "95", name: "Garum", state_id: "20" },
  { id: "96", name: "Gaya", state_id: "20" },
  { id: "97", name: "Gezawa", state_id: "20" },
  { id: "98", name: "Gwale", state_id: "20" },
  { id: "99", name: "Gwarzo", state_id: "20" },
  { id: "100", name: "Kabo", state_id: "20" },
  { id: "101", name: "Kano Municipal", state_id: "20" },
  { id: "102", name: "Karaye", state_id: "20" },
  { id: "103", name: "Kibiya", state_id: "20" },
  { id: "104", name: "Kiru", state_id: "20" },
  { id: "105", name: "Kumbotso", state_id: "20" },
  { id: "106", name: "Kunchi", state_id: "20" },
  { id: "107", name: "Kura", state_id: "20" },
  { id: "108", name: "Madobi", state_id: "20" },
  { id: "109", name: "Makoda", state_id: "20" },
  { id: "110", name: "Minjibir", state_id: "20" },
  { id: "111", name: "Nasarawa", state_id: "20" },
  { id: "112", name: "Rano", state_id: "20" },
  { id: "113", name: "Rimin Gado", state_id: "20" },
  { id: "114", name: "Rogo", state_id: "20" },
  { id: "115", name: "Shanono", state_id: "20" },
  { id: "116", name: "Sumaila", state_id: "20" },
  { id: "117", name: "Takai", state_id: "20" },
  { id: "118", name: "Tarauni", state_id: "20" },
  { id: "119", name: "Tofa", state_id: "20" },
  { id: "120", name: "Tsanyawa", state_id: "20" },
  { id: "121", name: "Tudun Wada", state_id: "20" },
  { id: "122", name: "Ungogo", state_id: "20" },
  { id: "123", name: "Warawa", state_id: "20" },
  { id: "124", name: "Wudil", state_id: "20" }
];

export const getLgasByStateId = (stateId: string): LGA[] => {
  return lgas.filter(lga => lga.state_id === stateId);
};
