-- Populate LGAs for all Nigerian states
-- This migration adds comprehensive LGA data for all states

-- Abia State LGAs
INSERT INTO lgas (name, state_id) VALUES 
('Aba North', (SELECT id FROM states WHERE name = 'Abia')),
('Aba South', (SELECT id FROM states WHERE name = 'Abia')),
('Arochukwu', (SELECT id FROM states WHERE name = 'Abia')),
('Bende', (SELECT id FROM states WHERE name = 'Abia')),
('Ikwuano', (SELECT id FROM states WHERE name = 'Abia')),
('Isiala Ngwa North', (SELECT id FROM states WHERE name = 'Abia')),
('Isiala Ngwa South', (SELECT id FROM states WHERE name = 'Abia')),
('Isuikwuato', (SELECT id FROM states WHERE name = 'Abia')),
('Obi Ngwa', (SELECT id FROM states WHERE name = 'Abia')),
('Ohafia', (SELECT id FROM states WHERE name = 'Abia')),
('Osisioma Ngwa', (SELECT id FROM states WHERE name = 'Abia')),
('Ugwunagbo', (SELECT id FROM states WHERE name = 'Abia')),
('Ukwa East', (SELECT id FROM states WHERE name = 'Abia')),
('Ukwa West', (SELECT id FROM states WHERE name = 'Abia')),
('Umuahia North', (SELECT id FROM states WHERE name = 'Abia')),
('Umuahia South', (SELECT id FROM states WHERE name = 'Abia')),
('Umu Nneochi', (SELECT id FROM states WHERE name = 'Abia'))
ON CONFLICT DO NOTHING;

-- Adamawa State LGAs
INSERT INTO lgas (name, state_id) VALUES 
('Demsa', (SELECT id FROM states WHERE name = 'Adamawa')),
('Fufure', (SELECT id FROM states WHERE name = 'Adamawa')),
('Ganye', (SELECT id FROM states WHERE name = 'Adamawa')),
('Girei', (SELECT id FROM states WHERE name = 'Adamawa')),
('Gombi', (SELECT id FROM states WHERE name = 'Adamawa')),
('Guyuk', (SELECT id FROM states WHERE name = 'Adamawa')),
('Hong', (SELECT id FROM states WHERE name = 'Adamawa')),
('Jada', (SELECT id FROM states WHERE name = 'Adamawa')),
('Lamurde', (SELECT id FROM states WHERE name = 'Adamawa')),
('Madagali', (SELECT id FROM states WHERE name = 'Adamawa')),
('Maiha', (SELECT id FROM states WHERE name = 'Adamawa')),
('Mayo-Belwa', (SELECT id FROM states WHERE name = 'Adamawa')),
('Michika', (SELECT id FROM states WHERE name = 'Adamawa')),
('Mubi North', (SELECT id FROM states WHERE name = 'Adamawa')),
('Mubi South', (SELECT id FROM states WHERE name = 'Adamawa')),
('Numan', (SELECT id FROM states WHERE name = 'Adamawa')),
('Shelleng', (SELECT id FROM states WHERE name = 'Adamawa')),
('Song', (SELECT id FROM states WHERE name = 'Adamawa')),
('Toungo', (SELECT id FROM states WHERE name = 'Adamawa')),
('Yola North', (SELECT id FROM states WHERE name = 'Adamawa')),
('Yola South', (SELECT id FROM states WHERE name = 'Adamawa'))
ON CONFLICT DO NOTHING;

-- Lagos State LGAs (additional to existing ones)
INSERT INTO lgas (name, state_id) VALUES 
('Agege', (SELECT id FROM states WHERE name = 'Lagos')),
('Ajeromi-Ifelodun', (SELECT id FROM states WHERE name = 'Lagos')),
('Badagry', (SELECT id FROM states WHERE name = 'Lagos')),
('Epe', (SELECT id FROM states WHERE name = 'Lagos')),
('Eti-Osa', (SELECT id FROM states WHERE name = 'Lagos')),
('Ibeju-Lekki', (SELECT id FROM states WHERE name = 'Lagos')),
('Ifako-Ijaiye', (SELECT id FROM states WHERE name = 'Lagos')),
('Ikorodu', (SELECT id FROM states WHERE name = 'Lagos')),
('Kosofe', (SELECT id FROM states WHERE name = 'Lagos')),
('Lagos Mainland', (SELECT id FROM states WHERE name = 'Lagos')),
('Mushin', (SELECT id FROM states WHERE name = 'Lagos')),
('Ojo', (SELECT id FROM states WHERE name = 'Lagos')),
('Oshodi-Isolo', (SELECT id FROM states WHERE name = 'Lagos')),
('Shomolu', (SELECT id FROM states WHERE name = 'Lagos')),
('Surulere', (SELECT id FROM states WHERE name = 'Lagos'))
ON CONFLICT DO NOTHING;

-- Kano State LGAs
INSERT INTO lgas (name, state_id) VALUES 
('Ajingi', (SELECT id FROM states WHERE name = 'Kano')),
('Albasu', (SELECT id FROM states WHERE name = 'Kano')),
('Bagwai', (SELECT id FROM states WHERE name = 'Kano')),
('Bebeji', (SELECT id FROM states WHERE name = 'Kano')),
('Bichi', (SELECT id FROM states WHERE name = 'Kano')),
('Bunkure', (SELECT id FROM states WHERE name = 'Kano')),
('Dala', (SELECT id FROM states WHERE name = 'Kano')),
('Dambatta', (SELECT id FROM states WHERE name = 'Kano')),
('Dawakin Kudu', (SELECT id FROM states WHERE name = 'Kano')),
('Dawakin Tofa', (SELECT id FROM states WHERE name = 'Kano')),
('Doguwa', (SELECT id FROM states WHERE name = 'Kano')),
('Fagge', (SELECT id FROM states WHERE name = 'Kano')),
('Gabasawa', (SELECT id FROM states WHERE name = 'Kano')),
('Garko', (SELECT id FROM states WHERE name = 'Kano')),
('Garum', (SELECT id FROM states WHERE name = 'Kano')),
('Mallam', (SELECT id FROM states WHERE name = 'Kano')),
('Gaya', (SELECT id FROM states WHERE name = 'Kano')),
('Gezawa', (SELECT id FROM states WHERE name = 'Kano')),
('Gwale', (SELECT id FROM states WHERE name = 'Kano')),
('Gwarzo', (SELECT id FROM states WHERE name = 'Kano')),
('Kabo', (SELECT id FROM states WHERE name = 'Kano')),
('Kano Municipal', (SELECT id FROM states WHERE name = 'Kano')),
('Karaye', (SELECT id FROM states WHERE name = 'Kano')),
('Kibiya', (SELECT id FROM states WHERE name = 'Kano')),
('Kiru', (SELECT id FROM states WHERE name = 'Kano')),
('Kumbotso', (SELECT id FROM states WHERE name = 'Kano')),
('Kunchi', (SELECT id FROM states WHERE name = 'Kano')),
('Kura', (SELECT id FROM states WHERE name = 'Kano')),
('Madobi', (SELECT id FROM states WHERE name = 'Kano')),
('Makoda', (SELECT id FROM states WHERE name = 'Kano')),
('Minjibir', (SELECT id FROM states WHERE name = 'Kano')),
('Nasarawa', (SELECT id FROM states WHERE name = 'Kano')),
('Rano', (SELECT id FROM states WHERE name = 'Kano')),
('Rimin Gado', (SELECT id FROM states WHERE name = 'Kano')),
('Rogo', (SELECT id FROM states WHERE name = 'Kano')),
('Shanono', (SELECT id FROM states WHERE name = 'Kano')),
('Sumaila', (SELECT id FROM states WHERE name = 'Kano')),
('Takai', (SELECT id FROM states WHERE name = 'Kano')),
('Tarauni', (SELECT id FROM states WHERE name = 'Kano')),
('Tofa', (SELECT id FROM states WHERE name = 'Kano')),
('Tsanyawa', (SELECT id FROM states WHERE name = 'Kano')),
('Tudun Wada', (SELECT id FROM states WHERE name = 'Kano')),
('Ungogo', (SELECT id FROM states WHERE name = 'Kano')),
('Warawa', (SELECT id FROM states WHERE name = 'Kano')),
('Wudil', (SELECT id FROM states WHERE name = 'Kano'))
ON CONFLICT DO NOTHING;

-- Rivers State LGAs
INSERT INTO lgas (name, state_id) VALUES 
('Abua/Odual', (SELECT id FROM states WHERE name = 'Rivers')),
('Ahoada East', (SELECT id FROM states WHERE name = 'Rivers')),
('Ahoada West', (SELECT id FROM states WHERE name = 'Rivers')),
('Akuku-Toru', (SELECT id FROM states WHERE name = 'Rivers')),
('Andoni', (SELECT id FROM states WHERE name = 'Rivers')),
('Asari-Toru', (SELECT id FROM states WHERE name = 'Rivers')),
('Bonny', (SELECT id FROM states WHERE name = 'Rivers')),
('Degema', (SELECT id FROM states WHERE name = 'Rivers')),
('Eleme', (SELECT id FROM states WHERE name = 'Rivers')),
('Emohua', (SELECT id FROM states WHERE name = 'Rivers')),
('Etche', (SELECT id FROM states WHERE name = 'Rivers')),
('Gokana', (SELECT id FROM states WHERE name = 'Rivers')),
('Ikwerre', (SELECT id FROM states WHERE name = 'Rivers')),
('Khana', (SELECT id FROM states WHERE name = 'Rivers')),
('Obio/Akpor', (SELECT id FROM states WHERE name = 'Rivers')),
('Ogba/Egbema/Ndoni', (SELECT id FROM states WHERE name = 'Rivers')),
('Ogu/Bolo', (SELECT id FROM states WHERE name = 'Rivers')),
('Okrika', (SELECT id FROM states WHERE name = 'Rivers')),
('Omuma', (SELECT id FROM states WHERE name = 'Rivers')),
('Opobo/Nkoro', (SELECT id FROM states WHERE name = 'Rivers')),
('Oyigbo', (SELECT id FROM states WHERE name = 'Rivers')),
('Port Harcourt', (SELECT id FROM states WHERE name = 'Rivers')),
('Tai', (SELECT id FROM states WHERE name = 'Rivers'))
ON CONFLICT DO NOTHING;

-- Kaduna State LGAs
INSERT INTO lgas (name, state_id) VALUES 
('Birnin Gwari', (SELECT id FROM states WHERE name = 'Kaduna')),
('Chikun', (SELECT id FROM states WHERE name = 'Kaduna')),
('Giwa', (SELECT id FROM states WHERE name = 'Kaduna')),
('Igabi', (SELECT id FROM states WHERE name = 'Kaduna')),
('Ikara', (SELECT id FROM states WHERE name = 'Kaduna')),
('Jaba', (SELECT id FROM states WHERE name = 'Kaduna')),
('Jema''a', (SELECT id FROM states WHERE name = 'Kaduna')),
('Kachia', (SELECT id FROM states WHERE name = 'Kaduna')),
('Kaduna North', (SELECT id FROM states WHERE name = 'Kaduna')),
('Kaduna South', (SELECT id FROM states WHERE name = 'Kaduna')),
('Kagarko', (SELECT id FROM states WHERE name = 'Kaduna')),
('Kajuru', (SELECT id FROM states WHERE name = 'Kaduna')),
('Kaura', (SELECT id FROM states WHERE name = 'Kaduna')),
('Kauru', (SELECT id FROM states WHERE name = 'Kaduna')),
('Kubau', (SELECT id FROM states WHERE name = 'Kaduna')),
('Kudan', (SELECT id FROM states WHERE name = 'Kaduna')),
('Lere', (SELECT id FROM states WHERE name = 'Kaduna')),
('Makarfi', (SELECT id FROM states WHERE name = 'Kaduna')),
('Sabon Gari', (SELECT id FROM states WHERE name = 'Kaduna')),
('Sanga', (SELECT id FROM states WHERE name = 'Kaduna')),
('Soba', (SELECT id FROM states WHERE name = 'Kaduna')),
('Zangon Kataf', (SELECT id FROM states WHERE name = 'Kaduna')),
('Zaria', (SELECT id FROM states WHERE name = 'Kaduna'))
ON CONFLICT DO NOTHING;
