// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdgustwryjkgvedpcbyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkZ3VzdHdyeWprZ3ZlZHBjYnl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NTQ0MjQsImV4cCI6MjA3MjQzMDQyNH0.1Hf2hkqhsoYX_geGds--ml9Rp5Y40FDw4gNUKdjtMZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});